In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

c:\Users\yaksh\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
# Retreiving the dataset
group1_df = pd.read_csv("data\KSI_Project Dataset.csv")

In [29]:
group1_df.head()

,OBJECTID,INDEX,ACCNUM,DATE,TIME,STREET1,STREET2,OFFSET,ROAD_CLASS,DISTRICT,...,REDLIGHT,ALCOHOL,DISABILITY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,DIVISION,x,y
0,1,3389067,893184.0,1/1/2006 10:00:00 AM,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,...,NaN,Yes,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55,635468.3685,4.839881e+06
1,2,3389068,893184.0,1/1/2006 10:00:00 AM,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,...,NaN,Yes,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55,635468.3685,4.839881e+06
2,3,3389069,893184.0,1/1/2006 10:00:00 AM,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,...,NaN,Yes,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55,635468.3685,4.839881e+06
3,4,3389070,893184.0,1/1/2006 10:00:00 AM,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,...,NaN,Yes,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55,635468.3685,4.839881e+06
4,5,3389071,893184.0,1/1/2006 10:00:00 AM,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,...,NaN,Yes,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55,635468.3685,4.839881e+06

In [6]:
group1_df.shape

(18957, 54)

In [5]:
# Columns findings
group1_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18957 entries, 0 to 18956
Data columns (total 54 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   OBJECTID           18957 non-null  int64
 1   INDEX              18957 non-null  int64
 2   ACCNUM             14027 non-null  float64
 3   DATE               18957 non-null  str
 4   TIME               18957 non-null  int64
 5   STREET1            18957 non-null  str
 6   STREET2            17251 non-null  str
 7   OFFSET             3820 non-null   str
 8   ROAD_CLASS         18471 non-null  str
 9   DISTRICT           18728 non-null  str
 10  LATITUDE           18957 non-null  float64
 11  LONGITUDE          18957 non-null  float64
 12  ACCLOC             13501 non-null  str
 13  TRAFFCTL           18882 non-null  str
 14  VISIBILITY         18933 non-null  str
 15  LIGHT              18953 non-null  str
 16  RDSFCOND           18928 non-null  str
 17  ACCLASS            18956 non-null  str
 18  IMPACTYPE          18930 non-null  str
 19  INVTYPE            18941 non-null  str
 20  INVAGE             18957 non-null  str
 21  INJURY             10060 non-null  str
 22  FATAL_NO           870 non-null    float64
 23  INITDIR            13680 non-null  str
 24  VEHTYPE            15470 non-null  str
 25  MANOEUVER          11004 non-null  str
 26  DRIVACT            9668 non-null   str
 27  DRIVCOND           9666 non-null   str
 28  PEDTYPE            3229 non-null   str
 29  PEDACT             3227 non-null   str
 30  PEDCOND            3246 non-null   str
 31  CYCLISTYPE         805 non-null    str
 32  CYCACT             802 non-null    str
 33  CYCCOND            800 non-null    str
 34  PEDESTRIAN         7688 non-null   str
 35  CYCLIST            1986 non-null   str
 36  AUTOMOBILE         17230 non-null  str
 37  MOTORCYCLE         1684 non-null   str
 38  TRUCK              1169 non-null   str
 39  TRSN_CITY_VEH      1148 non-null   str
 40  EMERG_VEH          49 non-null     str
 41  PASSENGER          7183 non-null   str
 42  SPEEDING           2694 non-null   str
 43  AG_DRIV            9836 non-null   str
 44  REDLIGHT           1577 non-null   str
 45  ALCOHOL            808 non-null    str
 46  DISABILITY         493 non-null    str
 47  HOOD_158           18957 non-null  str
 48  NEIGHBOURHOOD_158  18957 non-null  str
 49  HOOD_140           18957 non-null  str
 50  NEIGHBOURHOOD_140  18957 non-null  str
 51  DIVISION           18957 non-null  str
 52  x                  18957 non-null  float64
 53  y                  18957 non-null  float64
dtypes: float64(6), int64(3), str(45)
memory usage: 12.8 MB

In [9]:
# null values :
group1_df.isnull().sum().sum()

np.int64(384930)

In [40]:
null_cols = group1_df.columns[group1_df.isnull().any()]     # any columns which has null values
(group1_df[null_cols].isnull().sum()/18957)*100    # Total nulls in each of them.

ACCNUM           26.006225
STREET2           8.999314
OFFSET           79.849132
ROAD_CLASS        2.563697
DISTRICT          1.207997
ACCLOC           28.780925
TRAFFCTL          0.395632
VISIBILITY        0.126602
LIGHT             0.021100
RDSFCOND          0.152978
ACCLASS           0.005275
IMPACTYPE         0.142428
INVTYPE           0.084402
INJURY           46.932532
FATAL_NO         95.410666
INITDIR          27.836683
VEHTYPE          18.394261
MANOEUVER        41.952841
DRIVACT          49.000369
DRIVCOND         49.010919
PEDTYPE          82.966714
PEDACT           82.977264
PEDCOND          82.877038
CYCLISTYPE       95.753548
CYCACT           95.769373
CYCCOND          95.779923
PEDESTRIAN       59.445060
CYCLIST          89.523659
AUTOMOBILE        9.110091
MOTORCYCLE       91.116738
TRUCK            93.833412
TRSN_CITY_VEH    93.944189
EMERG_VEH        99.741520
PASSENGER        62.108983
SPEEDING         85.788891
AG_DRIV          48.114153
REDLIGHT         91.681173
ALCOHOL          95.737722
DISABILITY       97.399378
dtype: float64

In [ ]:
len(null_cols)      # 39 columns have null values alteast once or more than it

39

In [32]:
group1_df.nunique()  # finding the target column

OBJECTID             18957
INDEX                18957
ACCNUM                4955
DATE                  4128
TIME                  1341
STREET1               1942
STREET2               2822
OFFSET                 494
ROAD_CLASS              11
DISTRICT                 4
LATITUDE              4783
LONGITUDE             5202
ACCLOC                  10
TRAFFCTL                10
VISIBILITY               8
LIGHT                    9
RDSFCOND                 9
ACCLASS                  3
IMPACTYPE               10
INVTYPE                 19
INVAGE                  21
INJURY                   4
FATAL_NO                78
INITDIR                  5
VEHTYPE                 32
MANOEUVER               16
DRIVACT                 13
DRIVCOND                10
PEDTYPE                 16
PEDACT                  15
PEDCOND                 10
CYCLISTYPE              22
CYCACT                  11
CYCCOND                 10
PEDESTRIAN               1
CYCLIST                  1
AUTOMOBILE               1
MOTORCYCLE               1
TRUCK                    1
TRSN_CITY_VEH            1
EMERG_VEH                1
PASSENGER                1
SPEEDING                 1
AG_DRIV                  1
REDLIGHT                 1
ALCOHOL                  1
DISABILITY               1
HOOD_158               159
NEIGHBOURHOOD_158      159
HOOD_140               141
NEIGHBOURHOOD_140      141
DIVISION                17
x                     6099
y                     6099
dtype: int64

In [37]:
group1_df['ACCLASS'].unique() # Target columns

<ArrowStringArray>
['Non-Fatal Injury', 'Fatal', 'Property Damage O', nan]
Length: 4, dtype: str

In [21]:
# basic statistics
group1_df.describe()

,OBJECTID,INDEX,ACCNUM,TIME,LATITUDE,LONGITUDE,FATAL_NO,x,y
count,18957.000000,1.895700e+04,1.402700e+04,18957.000000,18957.000000,18957.000000,870.000000,18957.000000,1.895700e+04
mean,9479.000000,3.994181e+07,5.576714e+08,1364.956428,43.710299,-79.396490,28.752874,629181.568576,4.840951e+06
std,5472.558862,3.749731e+07,1.180026e+09,631.310388,0.056294,0.104484,17.657001,8364.337712,6.324585e+03
min,1.000000,3.363207e+06,2.530100e+04,0.000000,43.589678,-79.638390,1.000000,609625.702600,4.827328e+06
25%,4740.000000,5.408154e+06,1.034561e+06,924.000000,43.661727,-79.471469,14.000000,623177.000800,4.835532e+06
50%,9479.000000,7.820656e+06,1.220029e+06,1450.000000,43.702346,-79.397388,27.500000,629199.077800,4.840070e+06
75%,14218.000000,8.092292e+07,1.386958e+06,1852.000000,43.755945,-79.318286,42.000000,635424.041900,4.846036e+06
max,18957.000000,8.180752e+07,4.008024e+09,2359.000000,43.855445,-79.122974,78.000000,651024.087800,4.857444e+06

In [23]:
# stats for the catgorical columns
group1_df.describe(include='str')

,DATE,STREET1,STREET2,OFFSET,ROAD_CLASS,DISTRICT,ACCLOC,TRAFFCTL,VISIBILITY,LIGHT,...,SPEEDING,AG_DRIV,REDLIGHT,ALCOHOL,DISABILITY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,DIVISION
count,18957,18957,17251,3820,18471,18728,13501,18882,18933,18953,...,2694,9836,1577,808,493,18957,18957,18957,18957,18957
unique,4128,1942,2822,494,11,4,10,10,8,9,...,1,1,1,1,1,159,159,141,141,17
top,8/17/2014 8:00:00 AM,YONGE ST,BATHURST ST,10 m West of,Major Arterial,Toronto and East York,At Intersection,No Control,Clear,Daylight,...,Yes,Yes,Yes,Yes,Yes,1,West Humber-Clairville,77,Waterfront Communities-The Island (77),D42
freq,35,403,156,61,13376,6328,8774,9021,16373,10779,...,2694,9836,1577,808,493,597,597,740,740,1813